---
# calico configuration
calico_version: "v3.30.2"
calico_custom_resources: default-calico-custom-resources.yml.j2

# felix configuration
calico_felix_config: default-calico-felix-config.yml.j2

# calicoctl configuration
calico_calicoctl_base_url: "https://github.com/projectcalico/calico/releases/download"
calico_calicoctl_dist: "linux-amd64"
calico_calicoctl_url: "{{ calico_calicoctl_base_url }}/{{ calico_version }}/calicoctl-{{ calico_calicoctl_dist }}"
