# Cluster deployment automation system
# Copyright 2025 Kevin Exton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
- name: Download Istio installation script
  ansible.builtin.uri:
    url: https://istio.io/downloadIstio
    method: GET
    return_content: yes
  register: istio_script

- name: Execute Istio installation script
  shell: |
    {{ istio_script.content }}
  args:
    creates: istio-1.26.2/bin/istioctl

- name: Add Istio bin directory to PATH
  lineinfile:
    path: /etc/environment
    line: 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ ansible_env.PWD }}/istio-1.26.2/bin"'
    regexp: '^PATH='
    backup: yes
