all:
  children:
    development:
      children:
        controller:
          hosts:
            dev-controller-01: &id001
              ansible_host: 10.152.1.10
          vars:
            can_ip_forward: true
            disk_size_gb: 40
            disk_type: pd-balanced
            group_labels:
              role: k8s
              tier: controller
            machine_type: e2-medium
        worker:
          hosts:
            dev-worker-01: &id002
              ansible_host: 10.152.1.11
          vars:
            can_ip_forward: true
            disk_size_gb: 40
            disk_type: pd-standard
            group_labels:
              role: k8s
              tier: worker
            machine_type: e2-medium
      hosts:
        dev-controller-01: *id001
        dev-worker-01: *id002
      vars:
        region: australia-southeast1
        env: development
