all:
  children:
    development:
      children:
        controller:
          hosts:
            dev-controller-01: &id003
              ansible_host: 10.152.1.10
          vars:
            can_ip_forward: true
            disk_size_gb: 40
            disk_type: pd-balanced
            group_labels:
              role: k8s
              tier: controller
            machine_type: e2-medium
        worker:
          children:
            general:
              hosts:
                dev-worker-general-01: &id001
                  ansible_host: 10.152.1.11
              vars: &id002
                can_ip_forward: true
                disk_size_gb: 40
                disk_type: pd-standard
                group_labels:
                  role: k8s
                  subgroup: general
                  tier: worker
                machine_type: e2-medium
                parent_group: worker
                subgroup_name: general
          hosts:
            dev-worker-general-01: *id001
          vars:
            can_ip_forward: true
            disk_size_gb: 40
            disk_type: pd-standard
            group_labels:
              role: k8s
              tier: worker
            machine_type: e2-medium
        worker_general:
          hosts:
            dev-worker-general-01: *id001
          vars: *id002
      hosts:
        dev-controller-01: *id003
        dev-worker-general-01: *id001
      vars:
        region: australia-southeast1
        env: development
