all:
  children:
    development:
      children:
        controller:
          hosts:
            dev-controller-01: &id005
              ansible_host: 10.152.1.10
          vars:
            can_ip_forward: true
            disk_size_gb: 100
            disk_type: pd-balanced
            group_labels:
              environment: development
              role: k8s
              tier: controller
            machine_type: e2-standard-2
        worker:
          children:
            general:
              hosts:
                dev-worker-general-01: &id001
                  ansible_host: 10.152.1.20
                dev-worker-general-02: &id002
                  ansible_host: 10.152.1.21
                dev-worker-general-03: &id003
                  ansible_host: 10.152.1.22
              vars: &id004
                can_ip_forward: true
                disk_size_gb: 100
                disk_type: pd-standard
                group_labels:
                  environment: development
                  role: k8s
                  subgroup: general
                  tier: worker
                machine_type: e2-standard-2
                parent_group: worker
                subgroup_name: general
          hosts:
            dev-worker-general-01: *id001
            dev-worker-general-02: *id002
            dev-worker-general-03: *id003
          vars:
            can_ip_forward: true
            disk_size_gb: 100
            disk_type: pd-standard
            group_labels:
              environment: development
              role: k8s
              tier: worker
            machine_type: e2-standard-2
        worker_general:
          hosts:
            dev-worker-general-01: *id001
            dev-worker-general-02: *id002
            dev-worker-general-03: *id003
          vars: *id004
      hosts:
        dev-controller-01: *id005
        dev-worker-general-01: *id001
        dev-worker-general-02: *id002
        dev-worker-general-03: *id003
      vars:
        region: australia-southeast1
        env: development
