---
all:
  children:
    development:
      hosts:
        dev-web-01:
          ansible_host: 10.0.1.10
        dev-db-01:
          ansible_host: 10.0.1.11
    staging:
      hosts:
        staging-web-01:
          ansible_host: 10.0.2.10
        staging-db-01:
          ansible_host: 10.0.2.11
    production:
      hosts:
        prod-web-01:
          ansible_host: 10.0.3.10
        prod-web-02:
          ansible_host: 10.0.3.11
        prod-db-01:
          ansible_host: 10.0.3.20
        prod-db-02:
          ansible_host: 10.0.3.21