all:
  children:
    development:
      children:
        controller:
          hosts:
            dev-controller-01: &id001
              ansible_host: 10.152.1.10
            dev-controller-02: &id002
              ansible_host: 10.152.2.10
            dev-controller-03: &id003
              ansible_host: 10.152.3.10
          vars:
            can_ip_forward: true
            disk_size_gb: 40
            disk_type: pd-balanced
            group_labels:
              role: k8s
              tier: controller
            lb_address: 10.152.0.6
            machine_type: e2-medium
        worker:
          hosts:
            dev-worker-01: &id004
              ansible_host: 10.152.1.11
            dev-worker-02: &id005
              ansible_host: 10.152.2.11
            dev-worker-03: &id006
              ansible_host: 10.152.3.11
          vars:
            can_ip_forward: true
            disk_size_gb: 40
            disk_type: pd-standard
            group_labels:
              role: k8s
              tier: worker
            machine_type: e2-medium
      hosts:
        dev-controller-01: *id001
        dev-controller-02: *id002
        dev-controller-03: *id003
        dev-worker-01: *id004
        dev-worker-02: *id005
        dev-worker-03: *id006
      vars:
        region: australia-southeast1
        env: development
