---
all:
  children:
    development:
      hosts:
        dev-01:
          ansible_host: 10.152.1.2
          zone_suffix: a
        dev-02:
          ansible_host: 10.152.2.2
          zone_suffix: b
        dev-03:
          ansible_host: 10.152.3.2
          zone_suffix: c
    staging:
      hosts:
        staging-web-01:
          ansible_host: 10.0.2.10
        staging-db-01:
          ansible_host: 10.0.2.11
    production:
      hosts:
        prod-web-01:
          ansible_host: 10.0.3.10
        prod-web-02:
          ansible_host: 10.0.3.11
        prod-db-01:
          ansible_host: 10.0.3.20
        prod-db-02:
          ansible_host: 10.0.3.21
