# Cluster deployment automation system
# Copyright 2025 Kevin Exton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
- name: Load default CouchDB secrets
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../.couchdb_secrets.yml"
    name: couchdb_secrets
  tags:
    - couchdb

- name: Create CouchDB namespace
  kubernetes.core.k8s:
    name: "{{ couchdb_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ couchdb_kubeconfig }}"
  tags:
    - couchdb

- name: Create CouchDB secret
  kubernetes.core.k8s:
    name: "{{ couchdb_release_name }}-couchdb"
    api_version: v1
    kind: Secret
    namespace: "{{ couchdb_namespace }}"
    definition:
      type: Opaque
      data:
        adminUsername: "{{ couchdb_admin_username | b64encode }}"
        adminPassword: "{{ (couchdb_admin_password | default(couchdb_secrets.admin_password, true)) | b64encode }}"
        cookieAuthSecret: "{{ (couchdb_cookie_auth_secret | default(couchdb_secrets.cookie_secret, true)) | b64encode }}"
        erlangCookie: "{{ (couchdb_erlang_cookie | default(couchdb_secrets.erlang_cookie, true)) | b64encode }}"
    state: present
    apply: true
    kubeconfig: "{{ couchdb_kubeconfig }}"
  tags:
    - couchdb

- name: Add CouchDB Helm repository
  kubernetes.core.helm_repository:
    name: couchdb
    repo_url: https://apache.github.io/couchdb-helm
    state: present
  tags:
    - couchdb

- name: Install CouchDB Helm chart
  kubernetes.core.helm:
    name: "{{ couchdb_release_name }}"
    chart_ref: couchdb/couchdb
    chart_version: "{{ couchdb_version }}"
    release_namespace: "{{ couchdb_namespace }}"
    create_namespace: true
    values_files: "{{ couchdb_values_files.results | map(attribute='dest') }}"
    state: present
  tags:
    - couchdb
