---
# containerd version and download settings
containerd_version: "2.1.3"
containerd_arch: "linux-amd64"
containerd_base_url: "https://github.com/containerd/containerd/releases/download"
containerd_filename: "containerd-{{ containerd_version }}-{{ containerd_arch }}.tar.gz"
containerd_download_url: "{{ containerd_base_url }}/v{{ containerd_version }}/{{ containerd_filename }}"
containerd_systemd_service_url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
containerd_config_file: "default-k8s-config.toml"

# containerd installation paths
containerd_prefix: "/usr/local"
containerd_bin_dir: "{{ containerd_prefix }}/bin"
containerd_systemd_dir: "{{ containerd_prefix }}/lib/systemd/system"
containerd_sbin_dir: "{{ containerd_prefix }}/sbin"
containerd_config_dir: "/etc/containerd"
containerd_cni_bin_dir: "/opt/cni/bin"

# runc version and download settings
containerd_runc_version: "1.3.0"
containerd_runc_arch: "amd64"
containerd_runc_base_url: "https://github.com/opencontainers/runc/releases/download"
containerd_runc_filename: "runc.{{ containerd_runc_arch }}"
containerd_runc_download_url: "{{ containerd_runc_base_url }}/v{{ containerd_runc_version }}/{{ containerd_runc_filename }}"

# cni-plugins version and download settings
containerd_cni_plugins_version: "1.7.1"
containerd_cni_plugins_arch: "linux-amd64"
containerd_cni_plugins_base_url: "https://github.com/containernetworking/plugins/releases/download"
containerd_cni_plugins_filename: "cni-plugins-{{ containerd_cni_plugins_arch }}-v{{ containerd_cni_plugins_version }}.tgz"
containerd_cni_plugins_download_url: "{{ containerd_cni_plugins_base_url }}/v{{ containerd_cni_plugins_version }}/{{ containerd_cni_plugins_filename }}"
