# Cluster deployment automation system
# Copyright 2025 Kevin Exton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
# containerd version and download settings
containerd_version: "2.1.3"
containerd_arch: "linux-amd64"
containerd_base_url: "https://github.com/containerd/containerd/releases/download"
containerd_filename: "containerd-{{ containerd_version }}-{{ containerd_arch }}.tar.gz"
containerd_download_url: "{{ containerd_base_url }}/v{{ containerd_version }}/{{ containerd_filename }}"
containerd_systemd_service_url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
containerd_config_file: "default-k8s-config.toml"

# runc version and download settings
runc_version: "1.3.0"
runc_arch: "amd64"
runc_base_url: "https://github.com/opencontainers/runc/releases/download"
runc_filename: "runc.{{ runc_arch }}"
runc_download_url: "{{ runc_base_url }}/v{{ runc_version }}/{{ runc_filename }}"

# cni-plugins version and download settings
cni_plugins_version: "1.7.1"
cni_plugins_arch: "linux-amd64"
cni_plugins_base_url: "https://github.com/containernetworking/plugins/releases/download"
cni_plugins_filename: "cni-plugins-{{ cni_plugins_arch }}-v{{ cni_plugins_version }}.tgz"
cni_plugins_download_url: "{{ cni_plugins_base_url }}/v{{ cni_plugins_version }}/{{ cni_plugins_filename }}"