---
# configuring kubectl
couchdb_kubeconfig: "{{ ansible_env.PWD }}/.kube/config"

# configuring helm
couchdb_release_name: relax
couchdb_version: 4.6.1
couchdb_namespace: couchdb

# configuring files and directories:
couchdb_working_dir: "{{ ansible_env.PWD }}/couchdb-deploy"
couchdb_values_templates:
  - values.yml.j2

# configuring couchdb
couchdb_uuid: ''
couchdb_admin_username: admin
couchdb_admin_password: ''
couchdb_cookie_auth_secret: ''
couchdb_erlang_cookie: ''
