---
- name: Delete GCP compute instances
  tags:
    - destroy
  google.cloud.gcp_compute_instance:
    name: "{{ item.key }}"
    zone: "{{ region }}-{{ item.value.zone_suffix | default('a') }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind | default('serviceaccount') }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: absent
  register: gcp_instance_delete_async
  async: 300
  poll: 0
  loop: "{{ hostvars | dict2items | selectattr('key', 'in', groups[target_group]) | list }}"

- name: Wait for all instances to be deleted
  tags:
    - destroy
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: gcp_instance_delete
  until: gcp_instance_delete.finished
  retries: 60
  delay: 5
  loop: "{{ gcp_instance_delete_async.results }}"

- name: Delete GCP VPC network
  tags:
    - destroy
  google.cloud.gcp_compute_network:
    name: "{{ vpc_name | default('ansible-vpc') }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind | default('serviceaccount') }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: absent
