---
- name: Create GCP VPC network
  tags:
    - deploy
  google.cloud.gcp_compute_network:
    name: "{{ vpc_name | default('ansible-vpc') }}"
    routing_config:
      routing_mode: REGIONAL
    auto_create_subnetworks: true
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind | default('serviceaccount') }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: present
  register: vpc

- name: Launch GCP compute instance
  tags:
    - deploy
  google.cloud.gcp_compute_instance:
    name: "{{ item.key }}"
    machine_type: "{{ machine_type | default('e2-micro') }}"
    zone: "{{ region }}-{{ item.value.zone_suffix | default('a') }}"
    disks:
      - auto_delete: true
        boot: true
        initialize_params:
          source_image: "{{ source_image | default('projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts') }}"
          disk_size_gb: "{{ disk_size_gb | default(20) }}"
    network_interfaces:
      - network: "{{ vpc }}"
        network_ip: "{{ item.value.ansible_host }}"
        access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
    tags:
      items: "{{ instance_tags | default(['ansible-vm']) }}"
    labels:
      environment: "{{ env }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind | default('serviceaccount') }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: present
  register: gcp_instance_async
  async: 300
  poll: 0
  loop: "{{ hostvars | dict2items | selectattr('key', 'in', groups[target_group]) | list }}"

- name: Wait for all instances to be created
  tags:
    - deploy
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: gcp_instance
  until: gcp_instance.finished
  retries: 60
  delay: 5
  loop: "{{ gcp_instance_async.results }}"

- name: Display instance information
  tags:
    - deploy
  debug:
    msg: "Instance {{ item.name }} created with private IP: {{ item.networkInterfaces[0].networkIP }} and external IP: {{ item.networkInterfaces[0].accessConfigs[0].natIP }}"
  loop: "{{ gcp_instance.results }}"
  when: item.networkInterfaces is defined
