---
- name: Update package cache
  package:
    update_cache: yes
    
- name: Install common packages
  package:
    name: "{{ common_packages }}"
    state: present
    
- name: Create admin user
  user:
    name: "{{ admin_user | default('admin') }}"
    groups: sudo
    shell: /bin/bash
    create_home: yes
    state: present
  when: admin_user is defined