# Cluster deployment automation system
# Copyright 2025 Kevin Exton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

---
- name: Install the Tekton operator
  kubernetes.core.k8s:
    src: "{{ tekton_operator_url }}"
    state: present
    kubeconfig: "{{ ansible_env.PWD }}/.kube/config"
    apply: true
  retries: 3
  delay: 10
  tags:
    - tekton

- name: Copy the Tekton configuration
  ansible.builtin.template:
    src: "{{ tekton_config }}"
    dest: "{{ ansible_env.PWD }}/tekton-config.yaml"
    mode: "0644"
  tags:
    - tekton

- name: Apply the Tekton configuration
  kubernetes.core.k8s:
    src: "{{ ansible_env.PWD }}/tekton-config.yaml"
    state: present
    kubeconfig: "{{ ansible_env.PWD }}/.kube/config"
    apply: true
  retries: 3
  delay: 10
  tags:
    - tekton
