---
- name: Deploy infrastructure to cloud
  hosts: localhost
  gather_facts: false
  connection: local
  
  vars:
    cloud_provider: "{{ provider | default('aws') }}"
    region: "{{ deployment_region | default('us-east-1') }}"
    
  tasks:
    - name: Include cloud-specific tasks
      include_tasks: "tasks/{{ cloud_provider }}-deploy.yml"
      when: cloud_provider in ['aws', 'azure', 'gcp']
      
    - name: Fail if unsupported cloud provider
      fail:
        msg: "Unsupported cloud provider: {{ cloud_provider }}"
      when: cloud_provider not in ['aws', 'azure', 'gcp']