---
env: development
debug: true
log_level: debug

gcp_service_account_file: "~/.gcp/ansible-stochastic-394206.json"
gcp_project: "stochastic-394206"
gcp_project_id: "90260082910"
vpc:
  selfLink: "https://www.googleapis.com/compute/v1/projects/stochastic-394206/global/networks/default"

# kubernetes configuration
kubeadm_config_template: kubernetes/development-kubeadm.yml.j2
advertise_address: "{{ hostvars['dev-controller-01']['ansible_host'] }}" 
