---
- name: Download and extract containerd
  ansible.builtin.unarchive:
    src: "{{ containerd_download_url }}"
    dest: "/usr/local"
    remote_src: yes
    creates: "/usr/local/bin/containerd"
  notify: restart containerd

- name: Create systemd service directory
  ansible.builtin.file:
    path: "/usr/local/lib/systemd/system"
    state: directory
    mode: '0755'

- name: Download the containerd systemd service unit
  ansible.builtin.get_url:
    url: "{{ containerd_systemd_service_url }}"
    dest: "/usr/local/lib/systemd/system/containerd.service"
  notify: restart containerd

- name: Enable and start containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started
    daemon_reload: yes

- name: Create sbin directory
  ansible.builtin.file:
    path: "/usr/local/sbin"
    state: directory
    mode: '0755'

- name: Download and install runc
  ansible.builtin.get_url:
    url: "{{ runc_download_url }}"
    dest: "/usr/local/sbin/runc"
    mode: '0755'

- name: Download and extract cni-plugins
  ansible.builtin.unarchive:
    src: "{{ cni_plugins_download_url }}"
    dest: "/opt/cni/bin"
    remote_src: yes
    creates: "/opt/cni/bin/bridge"
    mode: '0755'

- name: Copy containerd configuration
  ansible.builtin.copy:
    src: k8s-config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: restart containerd
